export const openingText = "THE STORY SO FAR....\n"+
  "\n"+
  "YOU ARE WALKING HOME ONE NIGHT WHEN YOU HEAR A GUNSHOT.\n"+
  "YOU FIND A DYING MAN LYING IN THE ROAD. HE MUTTERS THE WORDS;\n"+
  " 'THE WILD BUNCH...'\n"+
  "THE MAN WITH PATCH ON LEFT EYE...\n"+
  "THE MAN COUGHS AND DIES.\n"+
  "YOU PICKUP A COLT 45 THAT MUST BELONG TO THE MURDERER.\n"+
  "AT THAT MOMENT THE SHERIFF RIDES UP. HE SEES YOU WITH THE BODY AND THE GUN IN YOUR HAND\n"+
  "HE SHOUTS; 'DON''T MOVE OR I'LL FILL YOU FULL OF LEAD!'\n"+
  "YOU RUN OFF INTO THE NIGHT WITH BULLETS FLYING PAST YOUR HEAD\n"+
  "\n"+
  "PRESS ANY KEY"

